package com.micabytes.ink

internal enum class ContentType {
    CHOICE_ONCE,
    CHOICE_REPEATABLE,
    CONDITIONAL,
    CONDITIONAL_OPTION,
    FUNCTION,
    GATHER,
    KNOT,
    SEQUENCE_CYCLE,
    SEQUENCE_ONCE,
    SEQUENCE_SHUFFLE,
    SEQUENCE_STOP,
    STITCH,
    TEXT,
    VARIABLE_DECLARATION,
    VARIABLE_EXPRESSION,
    VARIABLE_RETURN,
    COMMENT_ONCE,
    COMMENT_REPEATABLE
}
