package com.micabytes.ink;

enum ContentType {
  CHOICE_ONCE,
  CHOICE_REPEATABLE,
  CONDITIONAL,
  FUNCTION,
  GATHER,
  KNOT,
  SEQUENCE_CYCLE,
  SEQUENCE_ONCE,
  SEQUENCE_SHUFFLE,
  SEQUENCE_STOP,
  STITCH,
  TEXT,
  VARIABLE_DECLARATION,
  VARIABLE_EXPRESSION,
}
